### ISSUE TITLE
Failed to activate the atom-path-intellisense package

### ISSUE THREAD

**Issue by go000** [apercova/atom-path-intellisense#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: [atom-path-intellisense](https://github.com/apercova/atom-path-intellisense) package 1.1.1

### Stack Trace

Failed to activate the atom-path-intellisense package

```
At Arguments to CompositeDisposable.add must have a .dispose() method

TypeError: Arguments to CompositeDisposable.add must have a .dispose() method
    at assertDisposable (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1175864)
    at CompositeDisposable.add (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1176832)
    at Object.consumeProvider (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:161712)
    at Object.consumeProvider_4 (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:161520)
    at Provider.t.exports.Provider.provide (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1029640)
    at ServiceHub.t.exports.ServiceHub.provide (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3012661)
    at Package.activateServices (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3020847)
    at Package.activateNow (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017902)
    at measure (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017226)
    at Package.measure (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3014857)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017086)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017029)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:382643)
    at ~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:899185
    at r (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:893791)
    at o (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032547)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032753)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -2:13.2.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:12.6.0 editor:join-lines (input.hidden-input)
  2x -2:11.7.0 core:move-left (input.hidden-input)
     -2:11.1.0 editor:join-lines (input.hidden-input)
     -2:08.9.0 autocomplete-plus:confirm (input.hidden-input)
     -2:06.9.0 core:backspace (input.hidden-input)
     -2:00.2.0 tree-view:remove (span.name.icon.css3-icon.medium-blue)
     -1:53.6.0 autocomplete-plus:confirm (input.hidden-input)
     -1:53.6.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:50.7.0 core:backspace (input.hidden-input)
  3x -1:49.9.0 core:save (input.hidden-input)
     -1:47.8.0 atom-beautify:beautify-editor (input.hidden-input)
  2x -1:47.5.0 core:save (input.hidden-input)
  2x -1:10.3.0 core:paste (input.hidden-input)
     -0:13.5.0 core:move-down (input.hidden-input)
     -0:13.1.0 autocomplete-plus:confirm (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-minify 0.8.0 
atom-path-intellisense 1.1.1 
atom-python-run 0.9.7 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-paths 2.12.2 
autocomplete-python 1.11.0 
autoprefixer 3.7.1 
browser-plus 0.0.98 
color-picker 2.3.0 
docblockr 0.13.7 
emmet 2.4.3 
file-icons 2.1.27 
highlight-selected 0.14.0 
javascript-snippets 1.2.1 
language-vue 0.24.0 
less-autocompile 1.0.0 
minimap 4.29.9 
open-in-browsers 0.0.30 
pigments 0.40.2 
quick-highlight 0.13.0 
sass-autocompile 0.13.5 
simplified-chinese-menu 5.3.5 
sync-settings 0.8.6 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by apercova** [comment]
Hi @go000 unfortunately this issue is related to: [autocomplete-plus 851 bug: https://github.com/atom/autocomplete-plus/issues/851](https://github.com/atom/autocomplete-plus/issues/851) which is still open.

As atom-path-intellisense depends on autocomplete-plus plackage as the natural atom´s mechanism to provide editor suggestions, this issue surely will be fixed further with an atom update.

I'll keep this issue open until we have a workaround or an atom update solves this bug.

regards.

**Comment by ajnauleau** [comment]
Having this issue as well when trying to reinstall the package after uninstalling it.

**Comment by apercova** [comment]
Hi @ajnauleau @go000 
There was an error on activating/disposing methods.

Release 1.2.0 is out!
This error is solved with this release.
Give it a try. 
Contributions are welcome.
